### ISSUE TITLE
Teacher's timetable responsive

### ISSUE THREAD

**Issue by georgestam** [georgestam/veronica#20]
The app is not fully responsive in mobile (i.e. they look almost the same in mobile and desktop, but is ok for this MVP stage). However, the teacher's timetable text should be within the card in mobile versions also.

This applies to both  `show` and `dashboard` teacher profile. 

![screen shot 2017-03-09 at 15 10 23](https://cloud.githubusercontent.com/assets/16335156/23753655/97c41d3c-04da-11e7-8065-8c38cb036399.png)

**Comment by ccrucianu** [comment]
hi everyone, 
By the way, teachers told me it is quite complicated choose every day one by one..Isn't there a way of choosing more days at the same time? You have to choose Monday and choose that day, then Friday, then...

**Comment by georgestam** [comment]
Yes, it is definitely not user-friendly. It is something to improve but I do not think that is critical at this stage. The critical issues I think that the ones related to the parents (who are the ones who pay).  I created a ticket here.

**Comment by georgestam** [comment]
Issue Implemented in 412e5ecbf72414b007f2c63623c83aab882f33bc
