### ISSUE TITLE
reset password email

### ISSUE THREAD

**Issue by ccrucianu** [georgestam/veronica#46]
A teacher did not receive his password reset when required it. I gave him a new password but when trying to sign in the webpage told me I had to confirm my email. But the problem is that it never sent another email. 

I think a good way is to send an email with the password from the very beginning....

**Comment by georgestam** [comment]
@ccrucianu issued fix in 2ad2385f33265d301f63fb806903ea4c19d5e3f1

Now users can recover passwords.
