### ISSUE TITLE
Delete profile error

### ISSUE THREAD

**Issue by ccrucianu** [georgestam/veronica#50]
![screen shot 2017-03-22 at 10 46 52](https://cloud.githubusercontent.com/assets/25704868/24194184/08471926-0eed-11e7-8718-106db0208999.png)

**Comment by ccrucianu** [comment]
I never was able to solve the reset password issue of that boy and he did a new profile. When trying to delete the old one, an error came up

**Comment by georgestam** [comment]
I am not sure how to move those issues into 'projects' (the trello-type board). @ccrucianu please create issues in the the ice-box within the project in the future.

I just fixed this issue in 04409984c2e75debe5f3c35e3283f2e7a366d2df. Now Users and teachers can be removed.
